# Podfile

# Select the appropriate platform below
# Specify the minimum supported iOS version (or later) required by Kiwi
platform :ios, '6.0'
# platform :osx

#
# Some other entries might already exist in the file
# ...
#
pod 'XcodeCoverage', '~>1.2.2'

# Add Kiwi as an exclusive dependency for the AmazingAppTests target
target :CalculatorStackTests, :exclusive => true do
  pod 'Kiwi'
end
